apiVersion: v1
kind: Namespace
metadata:
  name: ubu-acc
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-deploy-ubu-acc
  namespace: ubu-acc

---
# rolebinding only admin in namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-deploy-ubu-acc
  namespace: ubu-acc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: sa-deploy-ubu-acc
  namespace: ubu-acc
