apiVersion: v1
kind: Namespace
metadata:
  name: ubu-tst
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-deploy-ubu-tst
  namespace: ubu-tst

---
# rolebinding only admin in namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-deploy-ubu-tst
  namespace: ubu-tst
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: sa-deploy-ubu-tst
  namespace: ubu-tst
