apiVersion: v1
kind: Namespace
metadata:
  name: ubu-prd
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-deploy-ubu-prd
  namespace: ubu-prd

---
# rolebinding only admin in namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-deploy-ubu-prd
  namespace: ubu-prd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: sa-deploy-ubu-prd
  namespace: ubu-prd
