apiVersion: v1
kind: Namespace
metadata:
  name: ubu-dev
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-deploy-ubu-dev
  namespace: ubu-dev

---
# rolebinding only admin in namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-deploy-ubu-dev
  namespace: ubu-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: sa-deploy-ubu-dev
  namespace: ubu-dev
