apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ubu-apps
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/cpjboon/argocd-test
    path: applications/acc
