apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    name: ubu-apps
    namespace: openshift-gitops
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
    sourceRepos:
    - 'https://github.com/cpjboon/argocd-test'
kind: List
metadata:
  resourceVersion: ""
