apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ubu-psalter
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  project: ubu-apps
  source:
    repoURL: 'https://github.com/cpjboon/argocd-test'
    path: ubu-apps/overlays/acc
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
